# Generated by Django 5.0.6 on 2024-08-21 20:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plant_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='plant',
            name='species',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='description',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='image',
        ),
        migrations.RemoveField(
            model_name='wateringschedule',
            name='date',
        ),
        migrations.RemoveField(
            model_name='wateringschedule',
            name='time',
        ),
        migrations.AddField(
            model_name='plant',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wateringschedule',
            name='watering_interval',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='plant',
            name='categories',
            field=models.ManyToManyField(blank=True, to='myapp.category'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='last_watered',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='wateringschedule',
            name='plant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.plant'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.TextField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.plant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='photo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.photo'),
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Species',
        ),
    ]
