# Generated by Django 5.0.6 on 2024-08-21 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_photo_remove_plant_species_remove_plant_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='note',
        ),
    ]
