# Generated by Django 5.0.6 on 2024-08-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_notification_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(default='plant_photos/default_plant.jpg', upload_to='plant_photos/'),
        ),
    ]
